### PR TITLE
Linq to OrchardCore Extended

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by hishamco** [comment]
@Piedone seems building QueryProvider for OC will take time and needs a lot of work, I just rebulit on Linq2Db, Please let me know once you publish `Lombiq.HelpfulLibraries.LinqToDb` to NuGet

I think this is will be good to provide a stringly typed tables, indexes for OrchardCore database as well as custom tables - like what you did before -

**Comment by Piedone** [comment]
Actually, published https://www.nuget.org/packages/Lombiq.HelpfulLibraries.LinqToDb/ just a few hours ago. Let me know if you try it out.

**Comment by hishamco** [comment]
BTW I saw the `async` usage in the transaction, but where are the places that Linq2Db are executing the queries async?

**Comment by hishamco** [comment]
I think I will merge this for now and think how can I use `async` with `Lombiq.HelpfulLibraries.LinqToDb` by exposing properties in `OrchardDataContext` something similar to LINQ to SQL or EF

**Pull request merged**
